(() => {
'use strict';
const APP='renewal-radar', VERSION=1, KEY='randomvibez:renewal-radar:v1', MAX=30000, IMPORT=50000;
const $=s=>document.querySelector(s); const fields=['service','amount','frequency','renewal','route','cancelled','reference','notes']; let state=null;
function clean(v,n){return typeof v==='string'?v.trim().slice(0,n):''} function date(v){if(!v)return true;if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;let [y,m,d]=v.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));return y>=1000&&y<=9999&&x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d}
function record(input){if(!input||typeof input!=='object'||Array.isArray(input))return null;let r={};for(const k of fields){if(input[k]!==undefined&&typeof input[k]!=='string')return null;r[k]=clean(input[k]||'',k==='notes'?1200:k==='service'?120:k==='reference'?120:40)}return r.service&&date(r.renewal)&&date(r.cancelled)?r:null}
function valid(x){return x&&x.app===APP&&x.version===VERSION&&record(x.record)&&new Blob([JSON.stringify(x)]).size<=MAX?{app:APP,version:VERSION,record:record(x.record)}:null}
function save(x){let v=valid(x);if(!v)return false;try{let s=JSON.stringify(v);if(new Blob([s]).size>MAX)return false;localStorage.setItem(KEY,s);state=v;return true}catch(_){return false}}
function read(){try{let s=localStorage.getItem(KEY);return s&&new Blob([s]).size<=MAX?valid(JSON.parse(s)):null}catch(_){return null}}
function fmt(v){if(!v)return 'Not recorded';let [y,m,d]=v.split('-');return new Date(Date.UTC(+y,+m-1,+d)).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'})}
function text(p,v,t='span'){let n=document.createElement(t);n.textContent=v;p.append(n);return n}
function render(r){let box=$('#recordView');box.replaceChildren();if(!r){text(box,'No saved record yet.','p','muted');$('#mode').textContent='Start here';return}$('#mode').textContent='Saved locally';let h=text(box,r.service,'h3');h.className='record-title';let dl=document.createElement('dl');[['Amount',r.amount||'Not recorded'],['Frequency',r.frequency],['Next renewal',fmt(r.renewal)],['Cancellation route',r.route],['Cancellation date',fmt(r.cancelled)],['Reference',r.reference||'Not recorded']].forEach(([a,b])=>{text(dl,a,'dt');text(dl,b,'dd')});box.append(dl);if(r.notes){text(box,'Notes','h4');text(box,r.notes,'p')}let p=text(box,'Saved in this browser.','p');p.className='saved-label'}
function fill(r){fields.forEach(k=>{let e=$(`[name="${k}"]`);e.value=r?.[k]||''})}function status(m,bad=false){let e=$('#status');e.textContent=m;e.className='status'+(bad?' error':'')}
function download(n,c,t){let u=URL.createObjectURL(new Blob([c],{type:t})),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
$('#recordForm').addEventListener('submit',e=>{e.preventDefault();let r={};fields.forEach(k=>r[k]=$(`[name="${k}"]`).value);r=record(r);if(!r){status('Add a service and valid dates.',true);return}if(!save({app:APP,version:VERSION,record:r})){status('Could not save; your previous record was kept.',true);return}render(r);status('Saved locally.');});
$('#clearForm').onclick=()=>{fill(null);status('Form cleared; saved data is unchanged.')};$('#deleteRecord').onclick=()=>{try{localStorage.removeItem(KEY)}catch(_){}state=null;render(null);status('Saved record deleted from this browser.')};$('#printRecord').onclick=()=>{if(state)window.print()};$('#exportRecord').onclick=()=>{if(!state){status('Save a record before exporting.',true);return}download('renewal-radar-backup.json',JSON.stringify(state,null,2),'application/json');status('JSON backup downloaded; it is not encrypted.')};$('#importRecord').onchange=async e=>{let f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>IMPORT){status('Backup is too large (maximum 50 KB).',true);return}try{let x=valid(JSON.parse(await f.text()));if(!x||!save(x))throw Error();fill(x.record);render(x.record);status('Backup imported and saved locally.')}catch(_){status('Import rejected: use an unmodified Renewal Radar backup.',true)}};
state=read();fill(state?.record);render(state?.record);if(!state)status('Start with one service, trial, or renewal.');if(typeof window!=='undefined')window.RenewalRadar={record,valid,MAX,IMPORT};
})();